# \u9879\u76EE\u4E2D\u914D\u7F6E\u4E86 UserDetailsService \u7EC4\u4EF6\uFF0C\u4F1A\u7981\u7528\u8FD9\u91CC\u7684\u914D\u7F6E
spring.security.user.name=wenqiu
spring.security.user.password=123456
spring.security.user.roles=admin,common,hr,manager