server:
  port: 9999
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
#
person:
  name: '张三 \n 123'
  age: 18
  birthday: 2010/10/12 12:12:12
  like: true
  child:
    name: "李四 \n 456"
    age: 20
    birthday: 2018/10/12
    #    text: ["abc", "def"]
    text:
      - abc
      - def
      - |
        dogs:
          - name: 小黑
            age: 3
          - name: 小白
            age: 2
      # 注意：若多行文本，行与行之间没有缩进，则会把\n变成空格；否则会保留格式。
      - >
        dogs:
        - name: 小黑
        age: 3
          - name: 小白
            age: 2
  dogs:
    - name: 小黑
      age: 3
    - name: 小白
      age: 2
  cats:
    c1:
      name: 小蓝
      age: 2
    c2: { name: 小绿, age: 2 }