liteflow:
  rule-source: config/flow.el.xml

spring:
  application:
    name: boot-admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://repo.emon.vip:3306/mybatisdb?useSSL=false
    username: root
    password: root123
    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3
  # SBA beg
  # SpringBootAdminClient配置，url表示SpringBootAdminServer的地址
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          service-host-type: ip
  # SBA end


management:
  endpoints:
    #enabled-by-default: true # 除了shutdown其他的web都是开启的，这样配置后，默认也启用了shutdown，等效的配置可以是 management.endpoint.shutdown.enabled=true
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: false
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    git:
      enabled: true
      mode: full
    os:
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true

# management.info.env.enabled=true 才会显示下面的配置
info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@