spring.application.name=ai
#
# ===openai===
spring.ai.openai.base-url=https://api.xty.app
spring.ai.openai.api-key=sk-oqHbcKPTbyrLeEE7M59wsmZIQEtl3iaCVbUrKRXvRb6dyBtJ
# \u6DD8\u5B9D\u5145\u503C\u5F97\u5230\u7684api-key\uFF1B\u67E5\u8BE2\u7528\u91CF\uFF1Ahttps://cx.xty.app/#/;\u8BE5api-key\u4E0D\u652F\u6301 gpt-4o-mini
spring.ai.openai.chat.base-url=https://hk.xty.app
spring.ai.openai.chat.api-key=sk-aaBgZQzwyBgzyWGj21C245D642C1446f9d2aBd92971733C0
spring.ai.openai.chat.options.model=gpt-3.5-turbo
# \u9ED8\u8BA4 dall-e-3
spring.ai.openai.image.options.model=dall-e-3
#
# ===ollama===
# \u672C\u5730 Ollama \u9ED8\u8BA4\u672C\u5730\u5730\u5740\u4E3A 11434 \u7AEF\u53E3
spring.ai.ollama.base-url=http://localhost:11434
# \u6307\u5B9A\u8981\u4F7F\u7528\u7684\u6A21\u578B\u540D\u79F0\uFF08\u4E0E\u672C\u5730 Ollama \u4E2D\u62C9\u53D6\u7684\u540D\u79F0\u4E00\u81F4\uFF09
spring.ai.ollama.chat.options.model=qwq:latest
#spring.ai.ollama.chat.options.model=llama3.2:latest