server:
  port: 8080

spring:
  mvc:
    #修改静态资源匹配的规则，默认为：/**
    #static-path-pattern: /res/**
    #开启隐藏的_method支持
    hiddenmethod:
      filter:
        enabled: true
    #开启内容协商
    contentnegotiation:
      favor-parameter: true
    #web:
    #resources:
      #修改默认静态资源位置，修改之前为： /static (or /public or /resources or /META-INF/resources)
      #static-locations: [ "classpath:/staticalias" ]
      #禁用所有的静态资源
      #add-mappings: true
      #cache:
        #period: 1100